// meal-suggest/single-dishes.js — Kho MÓN MUA NGOÀI (~20 món: bún thịt nướng,
// gỏi cuốn, bún đậu, bánh mì, phở...). Cùng cấu trúc trường với MS_FULL_MENUS
// nên tái dùng được enrich + AI xếp hạng.
// mealType: "lunch" | "dinner" | "all" (all = hợp cả trưa lẫn tối).
// price: giá tham khảo VND/phần ngoài quán — dùng để lọc theo ngân sách.
// Món mua ngoài KHÔNG lọc theo nguyên liệu sẵn có (pantry).

const MS_SINGLE_DISHES = [
  { mealType: "all", title: "Bún thịt nướng chả giò", carb: "Bún tươi sợi nhỏ", protein: "Thịt nạc vai nướng + chả giò chiên ít dầu", soup: "Nước mắm chua ngọt pha sẵn", veggie: "Xà lách, rau thơm, giá, dưa leo", dessert: "—", parts: "bún, thịt heo nướng, chả giò, rau sống, đậu phộng", cal_pct: 0.38, price: 40000, nutritionNotes: "Món nướng thơm ngon, ăn kèm nhiều rau sống giải ngấy." },
  { mealType: "all", title: "Gỏi cuốn tôm thịt chấm tương", carb: "Bánh tráng gạo mỏng", protein: "Tôm sú luộc + thịt ba chỉ nạc", soup: "Tương đen đậu phộng chấm", veggie: "Xà lách, rau húng, bún lá, dưa leo", dessert: "—", parts: "tôm, thịt heo, bánh tráng, bún, rau sống, tương", cal_pct: 0.28, price: 35000, nutritionNotes: "Cuốn tươi không chiên, nhẹ bụng, giàu đạm tôm." },
  { mealType: "all", title: "Mẹt bún đậu mắm tôm", carb: "Bún lá ép miếng", protein: "Đậu hũ chiên giòn + chả cốm + thịt chân giò luộc", soup: "Mắm tôm chanh ớt đánh bông", veggie: "Rau kinh giới, tía tô, dưa leo", dessert: "—", parts: "bún lá, đậu hũ, chả cốm, thịt heo, mắm tôm, rau thơm", cal_pct: 0.40, price: 55000, nutritionNotes: "Mẹt dân dã đủ đạm, ăn kèm rau thơm kháng khuẩn." },
  { mealType: "lunch", title: "Bánh mì thịt nguội pate", carb: "Ổ bánh mì giòn", protein: "Pate gan + thịt nguội + chả lụa", soup: "—", veggie: "Dưa leo, đồ chua, rau mùi, ớt", dessert: "—", parts: "bánh mì, pate, thịt nguội, chả lụa, dưa leo, đồ chua", cal_pct: 0.38, price: 25000, nutritionNotes: "Bữa trưa gọn nhẹ, pate giàu sắt, ăn kèm đồ chua dễ tiêu." },
  { mealType: "all", title: "Phở bò tái nạm", carb: "Bánh phở tươi", protein: "Thăn bò tái + nạm bò hầm mềm", soup: "Nước dùng ninh quế hồi gừng", veggie: "Hành hoa, rau mùi, giá trụng, chanh ớt", dessert: "—", parts: "bánh phở, thịt bò, quế, hồi, gừng, hành, giá", cal_pct: 0.40, price: 55000, nutritionNotes: "Nước dùng trong, thịt bò tái giàu sắt giúp tỉnh táo." },
  { mealType: "all", title: "Phở gà ta lá chanh", carb: "Bánh phở tươi", protein: "Gà ta luộc xé phay", soup: "Nước dùng gà ninh xương thanh ngọt", veggie: "Lá chanh thái chỉ, hành hoa, giá", dessert: "—", parts: "bánh phở, thịt gà, lá chanh, hành, giá", cal_pct: 0.38, price: 50000, nutritionNotes: "Nhẹ hơn phở bò, nước gà thanh, hợp cả bữa tối." },
  { mealType: "all", title: "Bún bò Huế nạc", carb: "Bún sợi to", protein: "Bắp bò hoa + chả cua", soup: "Nước dùng sả ớt cay nồng", veggie: "Hoa chuối, giá, rau muống chẻ", dessert: "—", parts: "bún, bắp bò, chả cua, sả, ớt, hoa chuối, giá", cal_pct: 0.40, price: 50000, nutritionNotes: "Vị cay kích thích vị giác, bắp bò nạc giàu đạm." },
  { mealType: "all", title: "Hủ tiếu Nam Vang", carb: "Sợi hủ tiếu dai", protein: "Sườn non + thịt băm + tôm", soup: "Nước lèo củ cải ninh xương", veggie: "Hẹ, cần tây, giá, xà lách", dessert: "—", parts: "hủ tiếu, sườn heo, thịt băm, tôm, củ cải, hẹ, giá", cal_pct: 0.40, price: 50000, nutritionNotes: "Nước lèo ngọt tự nhiên từ củ cải, topping đầy đủ." },
  { mealType: "dinner", title: "Bánh cuốn thịt mộc nhĩ", carb: "Bánh cuốn tráng mỏng", protein: "Thịt nạc băm xào mộc nhĩ + chả lụa", soup: "Nước mắm chua ngọt", veggie: "Rau thơm, giá trụng, dưa leo", dessert: "—", parts: "bánh cuốn, thịt heo, mộc nhĩ, chả lụa, rau thơm", cal_pct: 0.28, price: 35000, nutritionNotes: "Bánh hấp mềm nhẹ, hợp bữa tối ít dầu mỡ." },
  { mealType: "all", title: "Cơm tấm sườn bì chả", carb: "Cơm tấm hạt nhỏ", protein: "Sườn nướng + bì heo + chả trứng", soup: "Canh cải đi kèm (tùy quán)", veggie: "Đồ chua, dưa leo, cà chua", dessert: "—", parts: "cơm tấm, sườn nướng, bì, chả trứng, đồ chua", cal_pct: 0.41, price: 55000, nutritionNotes: "Đặc sản Sài Gòn, đạm đa dạng, nhớ gọi ít mỡ hành." },
  { mealType: "lunch", title: "Cơm gà xối mỡ (lườn gà)", carb: "Cơm nấu nước luộc gà", protein: "Lườn gà roti bỏ da", soup: "Canh cải nấu gừng", veggie: "Dưa leo, rau răm", dessert: "—", parts: "cơm, lườn gà, gừng, cải, dưa leo", cal_pct: 0.40, price: 45000, nutritionNotes: "Chọn lườn bỏ da để giảm mỡ, cơm thơm béo vừa phải." },
  { mealType: "all", title: "Bún chả Hà Nội", carb: "Bún lá", protein: "Chả viên + chả miếng nướng than", soup: "Nước mắm chua ngọt + dưa góp", veggie: "Xà lách, kinh giới, tía tô", dessert: "—", parts: "bún, thịt nướng, nước mắm, dưa góp, rau thơm", cal_pct: 0.39, price: 45000, nutritionNotes: "Thịt nướng than thơm lừng, ăn kèm rau sống cân bằng." },
  { mealType: "dinner", title: "Cháo gà xé nấm hương", carb: "Gạo tẻ nấu cháo", protein: "Gà ta xé + nấm hương", soup: "Nước cháo sánh (kiêm món chính)", veggie: "Hành hoa, tía tô, gừng sợi", dessert: "—", parts: "gạo, thịt gà, nấm hương, tía tô, gừng", cal_pct: 0.27, price: 40000, nutritionNotes: "Cháo ấm bụng, dễ tiêu, hợp bữa tối và người mệt." },
  { mealType: "all", title: "Mì Quảng tôm thịt", carb: "Sợi mì Quảng nghệ vàng", protein: "Tôm + thịt ba chỉ rim", soup: "Nước lèo xâm xấp đậm đà", veggie: "Bắp chuối, giá, rau húng", dessert: "—", parts: "mì quảng, tôm, thịt heo, nghệ, đậu phộng, bánh tráng", cal_pct: 0.39, price: 45000, nutritionNotes: "Sợi nghệ đẹp mắt, nước ít mà đậm, ăn kèm bánh tráng." },
  { mealType: "all", title: "Bánh xèo tôm thịt", carb: "Bánh xèo bột gạo nghệ", protein: "Tôm + thịt ba chỉ + đỗ xanh", soup: "Nước mắm chua ngọt", veggie: "Cải xanh cuốn, rau thơm, giá", dessert: "—", parts: "bột gạo, tôm, thịt heo, đỗ xanh, cải xanh, giá", cal_pct: 0.38, price: 40000, nutritionNotes: "Vỏ giòn rụm, cuốn cải xanh giảm ngấy hiệu quả." },
  { mealType: "dinner", title: "Bún thang gà", carb: "Bún sợi nhỏ", protein: "Gà xé + trứng tráng sợi + giò lụa", soup: "Nước dùng tôm khô thanh tao", veggie: "Rau răm, nấm hương, củ cải khô", dessert: "—", parts: "bún, thịt gà, trứng, giò lụa, tôm khô, rau răm", cal_pct: 0.29, price: 50000, nutritionNotes: "Tinh hoa Hà Nội, topping đẹp mắt, nước thanh nhẹ." },
  { mealType: "all", title: "Bún riêu cua đồng", carb: "Bún sợi vừa", protein: "Riêu cua + đậu hũ + chả lá lốt", soup: "Nước riêu cua chua dịu", veggie: "Hoa chuối, giá, kinh giới, mắm tôm", dessert: "—", parts: "bún, cua đồng, đậu hũ, cà chua, hoa chuối", cal_pct: 0.37, price: 40000, nutritionNotes: "Cua đồng giàu canxi, vị chua thanh dễ ăn." },
  { mealType: "lunch", title: "Bánh ướt thịt nướng", carb: "Bánh ướt tráng mỏng", protein: "Thịt xiên nướng + nem chua", soup: "Nước mắm chua ngọt", veggie: "Giá, dưa leo, rau thơm", dessert: "—", parts: "bánh ướt, thịt nướng, nem, giá, dưa leo", cal_pct: 0.36, price: 35000, nutritionNotes: "Nhẹ hơn bánh mì, thịt xiên thơm, cuốn rau mát." },
  { mealType: "dinner", title: "Miến gà trộn", carb: "Miến dong", protein: "Gà xé + trứng non (tùy chọn)", soup: "Nước trộn xì dầu tỏi (khô)", veggie: "Rau cải, giá, hành phi ít", dessert: "—", parts: "miến, thịt gà, trứng, rau cải, giá", cal_pct: 0.27, price: 45000, nutritionNotes: "Món trộn khô ít nước, miến dai nhẹ bụng buổi tối." },
  { mealType: "all", title: "Xôi xéo gà xé", carb: "Xôi nếp nghệ dẻo", protein: "Gà xé + chả quế", soup: "—", veggie: "Dưa leo, hành phi ít", dessert: "—", parts: "xôi nếp, thịt gà, chả quế, dưa leo", cal_pct: 0.37, price: 30000, nutritionNotes: "Xôi no lâu, hợp bữa trưa bận rộn, nhớ ăn kèm dưa leo." }
];
